version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - query-backend
      - ollama
    restart: unless-stopped

  query-backend:
    build:
      context: ./query-backend
      dockerfile: Dockerfile
    ports:
      - "9061:9061"
    env_file:
      - ./query-backend/.env
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve

volumes:
  ollama_data:
