version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - query-backend
    restart: unless-stopped

  query-backend:
    build:
      context: ./query-backend
      dockerfile: Dockerfile
    ports:
      - "9061:9061"
    env_file:
      - ./query-backend/.env
    restart: unless-stopped


