version: "3.9"

services:
  agentic-jd-generator:
    build: .
    ports:
      - "5001:5001"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env
    restart: unless-stopped
