---
config:
  look: neo
---
flowchart TD
 subgraph subGraph0["Job Descriptions Experts Portal"]
        A1["Generate Job Description"]
        A2["Store Job Description"]
        A3["Read Job Description"]
        A4["Query Job Description"]
  end
 subgraph subGraph1["Agentic Job Description Generator"]
        B1["Generate JD API"]
        B2["Store JD API"]
        B3["Read JD API"]
  end
 subgraph subGraph2["JD Agents"]
        C1["JD Agent Orchestrator"]
        C2["Clarifier Agent"]
        C3["Generator Agent"]
        C4["Critique Agent"]
        C5["Compliance Agent"]
        C6["Rewrite Agent"]
        C7["Finalizer Agent"]
  end
 subgraph subGraph3["Job Description Data Store"]
        D1["SQL Lite"]
  end
 subgraph subGraph4["JD Vector Store"]
        G1["VectorDB"]
  end
 subgraph subGraph5["Job Description Embeddings and Query"]
        E1["Document Processor"]
        E2["Query Handler"]
  end
 subgraph subGraph6["Exernal System"]
        F1["LLM Embeddings Generator"]
  end
    A1 -- Generate Job Description --> B1
    B1 -- Generate Job Description --> C1
    C1 -- Clarify --> C2
    C1 -- Generate --> C3
    C1 -- Critique --> C4
    C1 -- Compliance --> C5
    C1 -- Rewrite --> C6
    C1 -- Final Polish --> C7
    A2 -- Save Job Description --> B2
    B2 -- Save Job Description --> D1
    D1 -- AsyncEvent::Processs Job Description --> E1
    E1 -- Generate Embeddings --> F1
    E1 -- Store Embeddings> --> G1
    A3 -- Read Job Description --> B3
    B3 -- Read Job Description --> D1
    A4 -- User Query --> E2
    E2 -- Generate Embeddings --> F1
    E2 -- GetResults --> G1
    D1@{ shape: cyl}
    G1@{ shape: cyl}
    style A1 fill:#f9f,stroke:#333,stroke-width:1px
    style A2 fill:#f9f,stroke:#333,stroke-width:1px
    style A3 fill:#f9f,stroke:#333,stroke-width:1px
    style A4 fill:#f9f,stroke:#333,stroke-width:1px
    style B1 fill:#bbf,stroke:#333,stroke-width:1px
    style B2 fill:#bbf,stroke:#333,stroke-width:1px
    style B3 fill:#bbf,stroke:#333,stroke-width:1px
    style C1 fill:#bfb,stroke:#333,stroke-width:1px
    style C2 fill:#bfb,stroke:#333,stroke-width:1px
    style C3 fill:#bfb,stroke:#333,stroke-width:1px
    style C4 fill:#bfb,stroke:#333,stroke-width:1px
    style C5 fill:#bfb,stroke:#333,stroke-width:1px
    style C6 fill:#bfb,stroke:#333,stroke-width:1px
    style C7 fill:#bfb,stroke:#333,stroke-width:1px
    style D1 fill:#fdd,stroke:#333,stroke-width:1px
    style G1 fill:#fdd,stroke:#333,stroke-width:1px
    style E1 fill:#ffd,stroke:#333,stroke-width:1px
    style E2 fill:#ffd,stroke:#333,stroke-width:1px
